### ISSUE TITLE
Reprojection in Python

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/clim-recal#1]
Add and document the reprojection code to BNG from this [PR](https://github.com/alan-turing-institute/dymechh/pull/31) into this repo. 

Additions to the code:

- [ ] Make sure we don't lose the time information in the index (currently the projected data has only an integer index from 1 to 360).
- [ ] Make sure we keep the 'projection_y_coordinate' and 'projection_x_coordinate' as well as `tasmax` as a data variable.

Currently we've been having to process the data post-fact with thiscode:

```  
data_proj = xr.open_rasterio(projected_tif_file)

time_index = xr.cftime_range(init_date, end_date, freq='D', calendar='360_day')
    
data_xr = xr.DataArray(data_proj.values,
dims=('time', 'projection_y_coordinate', 'projection_x_coordinate'),
coords={'time': time_index, 'projection_y_coordinate': data_proj['y'][:].values, 'projection_x_coordinate': data_proj['x'][:].values},
attrs={'units': '°C'},).transpose('time','projection_y_coordinate','projection_x_coordinate').to_dataset(name='tasmax')

data_xr.to_netcdf(f"{output_name}_projected.nc")

```

where `init_date` and `end_date` get read from the file name.

Something like this could be added to the original code before saving the file.

**Comment by AoifeHughes** [comment]
https://github.com/alan-turing-institute/clim-recal/tree/reprojection branch started - needs worked on

**Comment by crangelsmith** [comment]
Cool! I'm working on the resampling of issue #2, I'll start from [the environment](https://github.com/alan-turing-institute/dymechh/blob/5ddcdc9845c2f200adbf81bf1c2f5e135d54e2df/environment.yml) you had for this script. Let's keep it at the `python` level so we can use it for all the code.

**Comment by AoifeHughes** [comment]
Really curious, `conda install python=3.10.6 ` is needed because `python>3.11` mismatches GDAL versions

**Comment by AoifeHughes** [comment]
- [ ] check https://github.com/alan-turing-institute/clim-recal/tree/3-data-loader for other variables to see if they work or need solutions!

**Comment by AoifeHughes** [comment]
See https://github.com/alan-turing-institute/clim-recal/pull/16
