### ISSUE TITLE
Workshop follow up email

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/clim-recal#102]
Hello,

Thank you for joining us at the Turing Institute on Monday for a workshop on bias correction and how clim-recal can be further adapted to meet current needs of data providers and practitioners.

Attached to this email is a PDF of the workshop deck and a link to the workshop document: https://hackmd.io/@turing-es/BJi2xTara

In terms of next steps, we hope to stay in touch and explore further conversations and collaborations on the following:
- Workshop with public health end users in early 2024
- Bias correction methods review paper
- Documentation on assumptions/selection criteria used for the application of a BC method for a specific problem
- Documentation on how to use, interpret, and make a decision using BC results

If any of the following look like something you'd like to be part of, please let us know! Thank you again for making the time to participate in the workshop and contribute to an interesting discussion that will inform clim-recal and Turing Environment & Sustainability work in the future.

**Comment by dingaaling** [comment]
@mvakil-dewar - how does this look? Any changes you'd suggest? :) 

I'm thinking of sending on Wed or Thurs.

**Comment by mvakil-dewar** [comment]
@dingaaling This looks great, thanks for putting this together! 

Regarding the methods review paper and documentation, are these all planned to be carried out by the project team by end of March 2024? Just wanted to make sure before it was put out there as collaborative efforts :)

**Comment by dingaaling** [comment]
@mvakil-dewar - thanks for the comment! I think it depends on whether or not any one reaches out to collab and @RuthBowyer's capacity next year. I'm guessing the whole process will probably extend beyond March though
