### ISSUE TITLE
Meeting with Rachel Franklin

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/clim-recal#121]
I think this went well. Shall we add notes here @dingaaling ?

**Comment by griff-rees** [comment]
This was lovely and going forward see #124

**Comment by dingaaling** [comment]
#124 captures notes from the meeting with ibicus, but i think this issue is about a meeting with Rachel. Do notes from that meeting live somewhere?

As this meeting has already happened though and an issue was opened to have meetings regularly with Rachel #131 I think it's safe to close this though!
