### ISSUE TITLE
Add automated tests to determine the actual behaviour of the calendar mapping functions

### ISSUE THREAD

**Issue by andrewphilipsmith** [alan-turing-institute/clim-recal#132]
**The scope of this issue is just to add indicative automated tests. It does not require any changes to main pipeline code until we have determined the desired behaviour.**

To contribute to resolving #100 and #106, it would be helpful to have tests that determine the current behaviour of the calendar mapping functions. The tests should include (at least) the following scenarios:

* Test the behaviour of the bits of code referenced in this [comment](https://github.com/alan-turing-institute/clim-recal/issues/100#issuecomment-1927454827).

eg what is the actual difference between `data` and `data_360` from this line of code:
```python
data_360 = data.convert_calendar(dim="time", calendar="360_day", align_on="year")
```

What is in behaviour does the `enforce_date_dropping` function make? What is the difference between 
`data_dates_dropped` and `data_360` in this snipit?
```python
if data.time.dt.is_leap_year.any():
    data_dates_dropped = enforce_date_dropping(data, data_360)
```

* Test for a leap year and non-year
* When mapping from 365/366 days ==> 360 days, 
  * Do we just drop the extra days?
  * How should we handle 30th Feb and (for non-leap years) 29th Feb?

* When mapping from 360 days ==> 365/366 days, how should se add extra days? 

* See this spreadsheet for an example of how the different calendars map on different dates: https://thealanturininstitute-my.sharepoint.com/:x:/g/personal/a_smith_turing_ac_uk/EXPWO4JyXGxEpb-9cbY2KCQBTKkwst5aI68Ynt45eI7FIg?e=lWOR3V

# Sub tasks

- [x] Create test data files (eg one-pixel for a leap year and a non leap-year)
- [x] Write unittest for the `resample_hadukgrid` function within `python/resampling/resampling_hads.py`, asserting on the dimensions of the input and output data.
- [x] Write unittest for the `enforce_date_dropping` function within `python/resampling/resampling_hads.py`, asserting on the dimensions of the input and output data.

 ~Write unittest for `preprocess_data` in `python/debiasing/preprocess_data.py`, asserting on the dimensions of the input and output data.~ the `python/debiasing/pre_process_data.py` process may now be superseded. Will open a new ticket separately if needed.

**Comment by griff-rees** [comment]
Thanks @andrewphilipsmith. @aranas FYI: refactoring your work on #32 to check and automate testing is my focus, specifically:

- `python/resampling/check_calendar.py`
- `python/resampling/resampling_hads.py`
- `python/resampling/check_calendar_log.txt`

**Comment by griff-rees** [comment]
This issue is addressed in this branch and should be closable when merged: https://github.com/alan-turing-institute/clim-recal/pull/145
