### ISSUE TITLE
Topics for Wednesday 11 September 2024

### ISSUE THREAD

**Issue by griff-rees** [alan-turing-institute/clim-recal#163]
## Topics

- [x] Segfault error: run strategy discussed
- [x] Results on projected CPM of first day of year files, likely leap years.
    - First day of the year for each `CPM`
    - Will duplicate the next day
- [x] Including `hads` prior to December 1980
- [x] Documentation #161 (Monday next week)
- [x] Licensing for `python-cmethods` `fork`: #157 
- [x] Merge #152 ?

## Postponed

- Tickets
- Milestones

**Comment by andrewphilipsmith** [comment]
I will follow up on #157 as discussed.

**Comment by griff-rees** [comment]
@andrewphilipsmith: regarding #157 see #164

**Comment by griff-rees** [comment]
Meeting and initial actions complete.

**Comment by griff-rees** [comment]
Meeting and initial actions complete.
