### ISSUE TITLE
HADs vs UKCP calendar

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/clim-recal#18]
I've just noticed that the HADs data has a 365 days per year calendar, whilst the UKCP a 360-day one. To run the debiasing methods at the daily level we need a 1-1 correspondence. Any thoughts in what are the best way to do this @RuthBowyer?

If we are going to map the HADs to 360 days we could do it in the resampling step.

**Comment by RuthBowyer** [comment]
Ah this is a great idea @crangelsmith! - Previously I just used days 1-30 for each month from HADs - but this doesn't really work for February.  I believe we have spoken about this with MO folks before - I will check back on notes and let you know.

**Comment by crangelsmith** [comment]
Seems that xarray already has a methods to convert calendars this way, look at this: https://docs.xarray.dev/en/stable/generated/xarray.Dataset.convert_calendar.html

This is the transformation:

> From a standard calendar to a “360_day”, the following dates in the source array will be dropped:
> From a leap year:
> January 31st (31), April 1st (92), June 1st (153), August 1st (214), September 31st (275), December 1st (336)

> From a non-leap year:
> February 6th (37), April 20th (110), July 2nd (183), September 13th (256), November 25th (329)

I'll apply this when resampling.
