### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/clim-recal#25]
No tests have been implemented yet in python (shame on me :-( ). Tests that should be included (and on a CI):

- Reprojections (we've experienced that the re-projections grid can change slightly in different GDAL versions).
- Resampling  (resampling is based on an xarray/scipy implementation)
- Data loader (make sure data loading, clipping, and selecting is doing what are supposed to do).

**Comment by gmingas** [comment]
Closing as this is now under #58 and other issues.
