### ISSUE TITLE
Selecting Runs for processing

### ISSUE THREAD

**Issue by RuthBowyer** [alan-turing-institute/clim-recal#28]
Hi @japopeBAS! Myself and @gmingas have been working to identify four runs of the CPM, based on tasmax mean of means and 2nd highest/lowest thanks to your advice, to run initial BC for the other variables on. 

[Here is a markdown where we selected them](https://github.com/alan-turing-institute/clim-recal/blob/main/R/misc/Identifying_Runs.md) - would you advise a) Choosing the runs indicated across all timeslices (historic and future?) - which the .md indicates would therefore be Runs 05, Run03, Run08 and Run12, or b) focusing on a specific time period (eg the averages and 2nd extremes for the near future period, or ignoring historical)? 

Related question - I did this on the initial dataset we had already processed (whilst the new infill data was being processed) - am I correct in my assumption that the timeslices covered by the CPM prior to the infill data release are to your knowledge the same data (ie the years 2040-2060 haven't been re-run for all ensemble members for those years, and is literally just the infill years?) 

With sincerest thanks for you insights!

**Comment by japopeBAS** [comment]
Morning, 

Infill Data - The original time slices were not re-run, we slightly over run the start and end of the infill slices to check they are behaving the same, but we only include new data and not the test sections in the update, so the data you have here is unchanged. 

With respect to choosing the ensemble members, I would be happy with you using either:

a) The average over the whole time period ("Considering all together, suggests: Runs 05, Run03, Run08 and Run12") 

or

b) The historical (1980-2000) period (" Run 02 (2nd lowest), Run 04 & Run 03, and Run 11 (2nd lowest)")

I'd lean towards "a", however if you include the infill data would you need to re-do this analysis? My thoughts on "b" is based on the assumption that the bias correction validation will lean heavily on this period, so using this period to make the choice of ensemble members would also make sense. 

Hope that helps :)

James

**Comment by RuthBowyer** [comment]
Thanks James, really appreciate it! 

On reflection I think we need to include infill data in this analysis anyway - as there is a further historical period now (ie 2000-2020). Will run on the newly reprojected infill data and update!

**Comment by japopeBAS** [comment]
I wouldn't consider 2000-2020 a "historical" period, because the forcing scenario used begins in 2005 (and the driving models providing the large scale circulation conditions) were run in 2017, as such while those dates are in our past, they were predominantly in the models future.

**Comment by RuthBowyer** [comment]
> I wouldn't consider 2000-2020 a "historical" period, because the forcing scenario used begins in 2005 (and the driving models providing the large scale circulation conditions) were run in 2017, as such while those dates are in our past, they were predominantly in the models future.

This is super useful info, thank you!

**Comment by RuthBowyer** [comment]
Thanks again @japopeBAS  - [this has been run again to include the infill data,](https://github.com/alan-turing-institute/clim-recal/blob/InterimRuns/R/misc/Identifying_Runs.md) and using all time periods we we use: **Run05, Run07, Run08, Run06**
