### ISSUE TITLE
Reprojection script does not work with `environment.yml`

### ISSUE THREAD

**Issue by gmingas** [alan-turing-institute/clim-recal#30]
The main `environment.yml` file does not include the `gdal` library, which means the reprojection code in `https://github.com/alan-turing-institute/clim-recal/blob/main/bash/reproject_all.sh` fails. 

Additionally, when including the latest version of GDAL, the current output files in Azure are not reproducible. 

In order to reproduce the results, I had to create a new conda environment without using the `environment.yml` and with the following options (see related discussions [here](https://github.com/alan-turing-institute/clim-recal/issues/7#issuecomment-1430350835) and [here](https://github.com/alan-turing-institute/clim-recal/issues/1):
`conda create -n myenv python=3.10 gdal=3.4`

I also had to run the following in the Azure VM to give execution permissions and install the `parallel` package:
```
chmod +x ./reproject_one.sh
chmod +x ./reproject_all.sh
sudo apt-get update
sudo apt-get install parallel
```

When all the above was finished, I was able to reproduce the results. 

The documentation needs to be changed to reflect the above.

**Comment by aranas** [comment]
just checking, this here is the parallel tool that is being installed correct?
https://www.gnu.org/software/parallel/

**Comment by gmingas** [comment]
> just checking, this here is the parallel tool that is being installed correct? https://www.gnu.org/software/parallel/

Yes, this is the tool

**Comment by gmingas** [comment]
@aranas added instructions for this in the guidance branch
