### ISSUE TITLE
Crop rasters to the 3 cities of interest and process model data

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/clim-recal#34]
- [x]  Decide either area outline based on polygon/shapefile area definition, or a wider box (note - have used a particular shapefile method for the LCAT data but doesnt have to be the same for trial runs of data

Cities of interest: Glasgow, Manchester, London

Then, create a dataset for the 4 runs identified previously so as to have the same input data. This means:

- ~[x] Create a cropped version of the HADS UKgrid (obs data) for these runs/areas, grouped temporally for the calibration years (1980 - 2010)~
- [x]  ~As above, for years (2010 - 2020)~
- [x]  ~Create a cropped version of the CPM for these runs/areas, grouped temporally for the calibration years (1980 - 2010) -- i.e. will be across 2 sets of CPM rasters~
- [x]  ~As above, for years (2010 - 2020)~
- [x]  ~As above, for the projection years (2020 - 2080) ~
- [x] The R script in #44 should crop the CPM and HADs files (currently under Reprojected and Processed folders respectively) and place the cropped versions under a new directory. It should keep the same file names, folder hierarchy, temporal periods (one-year slices for CPM and monthly for HADs), file formats (`.tif` for CPM and `.nc` for HADs) and contents (e.g. coordinate names in netCDF files).
- [x] Load rasters into python to visually sense check + check names (GM)
- [x] updated hads calendar
- [x] creating new "Cropped" folder structure (Cropped/three_cities; ~Cropped/LCAT~), where intermediate HADs files live (both with updated resampling and original) *note: because there is no interim shapefile, the cropped LCAT data dataframes are in `Interim/{model}/Data_as_df/LCAT`*

**Comment by RuthBowyer** [comment]
I've ran this, as follows:

**FOR THE CPM (2.2km)**

The data grouped as it was in processing (grouped by time slice, with the slice 2000-2020 only grouped in decades for easier carving off to val and cal) are all in:

`mnt/vmfileshare/Interim/CPM/three.cities/<cityname>`

Where cityname is London, Manchester or Glasgow.
The four runs for the CPM ("05", "07", "08", "06") and 3 vars (tasmax, tasmin, pr) are all in that same folder

In the subdirectory `/grouped`:

- Calibration - Raster grouped for 1980 - 2010
- Validation - Raster grouped for 2010 (Winter) - 2020
- Projection  - 2020 (Winter) onwards 

**FOR HADS (Obs data)**

`mnt/vmfileshare/Interim/HadsUK/three.cities/<cityname>`

Where cityname is as above

These files are grouped by calibration and validation years as above

The shapefile crops used to derive the extents are in 'mnt/vmfileshare/shapefiles/three.cities'

The scripts used to process this data are `read_crop.fn.R` and `Cropping_rasters_to_three_cities.R` - these **will** be pushed soon to PR.

**Comment by RuthBowyer** [comment]
I've just noticed that how I pulled through the calibration dates for the CPM means 2010 is included, where is the corresponding HADs dataset, this is no the case. So I will re-run the grouping to account for this, but a work-around is just to subset out these final dates to match the length of the hads/observation date.

**Comment by RuthBowyer** [comment]
Following chat with @gmingas and @aranas I'm going to crop in the same temporal period as the input files (ie rather than grouping) and write the HADs crops to netcdfs
