### ISSUE TITLE
Apply bias correction method for 3 Target Cities (for MO)

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/clim-recal#36]
Deliverable: 1 method applied in Python and R to 3 cities, 4 runs, 3 variables

Cities:
- Glasgow
- Manchester
- London

For [Run05, Run07, Run08, Run06](https://github.com/alan-turing-institute/clim-recal/issues/28) for tasmax, tasmin, precip

[Choose a method of bias correction](https://docs.google.com/spreadsheets/d/18LIc8omSMTzOWM60aFNv1EZUl1qQN_DG8HFy1_0NdWk/edit?usp=sharing) or a library of bias correction methods (eg `cmethods`) 

We want to definitely have: Empirical Quantile Mapping, linear scaling, Scaled Distribution Mapping (`pycat`)** 

**I have the scripts the met office use if that is helpful -- 
The method used by the MO to bias correct this data in general is Scaled Distribution Mapping (SDM) via the `pycat` package.

However, [we had some issues implementing.](https://github.com/alan-turing-institute/clim-recal/issues/6#issuecomment-1441714791) 

It would be great for this to be a focus if someone is interested in applying a method to our 3 cities. 

- [x] pipeline working for Nonparametric Quantile Mapping
- [x] pipeline working for cmethods
- [x] remove unnecessary hardcoded lines
- [x] final run

**Comment by dingaaling** [comment]
@RuthBowyer suggests using multiple methods (e.g. in R and cmethods)

**Comment by RuthBowyer** [comment]
I've ran this using QM in qmap, the results are (currently in an R format file/list for assessing and further processing back to raster) located in: 

`ClimateData/Debiased/R/QuantileMapping/three.cities/`

Nice to have the pipeline set up etc, but this will probably be re-run when the obs data is sorted as in #32  - but means I can proceed to #39 with this data if still ongoing when I'm back next week. 

For future ref it takes about 30 mins to process all of them (3 cities, 4 runs, 3 vars) in qmap using `doqmapQUANT` (I will actually time it next time!) 

Scripts are [here](https://github.com/alan-turing-institute/clim-recal/blob/BC_three_cities/R/bias-correction-methods/apply_qmapQuant_to_crpd_df_fn.R) and [here](R/bias-correction-methods/ThreeCitiesQmap.RMD), will PR when updated Hads files
