### ISSUE TITLE
Grant LCAT access to Azure fileshare + Deliver Data

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/clim-recal#38]
If the data is in an Azure Storage account, you will need to configure access for someone regardless of whether they are on the subscription. An overview and details of different methods of providing access can be found on the Azure docs: [https://learn.microsoft.com/en-us/azure/storage/common/authorize-data-access](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fstorage%2Fcommon%2Fauthorize-data-access&data=05%7C01%7Cjding%40turing.ac.uk%7Cf62e8fcafe004298cb8308db9274f2f2%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638264803209861707%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0gI0qdrm9UgLRIJUr5gQlyu8QM1pOQYd3kDN%2FQeBS8o%3D&reserved=0)

If you do want to add external collaborators to an Azure subscription, they will first need to sign the acceptable use of Information Technology policy. Please see our [Azure guide on Mathison](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmathison.turing.ac.uk%2Fpage%2F2433%3FSearchId%3D285468%26utm_source%3Dinteract%26utm_medium%3Dgeneral_search%26utm_term%3Dazure%23add-people-to-subscription&data=05%7C01%7Cjding%40turing.ac.uk%7Cf62e8fcafe004298cb8308db9274f2f2%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638264803209861707%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=noT2h4q6BnXwVjfOfAlRMMaq899V1znwyo0xRYuEGhI%3D&reserved=0) for details on this.

- [x] Convo with LCAT about Data Delivery + send correct form for their needs
- [x] Identify who to grant access too
- [ ] Email Harry names/info to double check
- [ ] Work with RCP to grant access to Azure

Slack conversation with RCP: https://alan-turing-institute.slack.com/archives/C2GUZBYKC/p1697019789779279

**Comment by dingaaling** [comment]
Draft email to send to Emma/Jess/TTT, could I get your thoughts on this @RuthBowyer 😄 

Hello LCAT team!

As we get closer to sharing bias corrected data in September, there are a few logistical hurdles we'd like to discuss. The dataset that the DyME-CHH team is generating for LCAT will be stored on our Azure file share. The dataset will be available for download off of Azure until at least March 2024. In order to grant access to external to Turing collaborators, we have a few open questions/next steps:

1. Could you please share a list of names/emails of people who will be individually needing access to the Azure fileshare?
2. Every person with access will need to sign Turing's Acceptable Use of Information Technology Policy - https://mathison.turing.ac.uk/Utilities/Uploads/Handler/Uploader.ashx%3Farea=composer&filename=Acceptable+use+of+Information+Technology+Policy+V2.8.pdf&fileguid=9c5ebbf9-1a2d-4e48-bcec-e67fe9c50956

The next steps are that after we have received the list of names/emails from you, we will share the policy to be signed, and finally in September grant access to the Azure fileshare for access to the bias corrected dataset.

Thanks for your help with this - almost to the finish line!
Jen

**Comment by RuthBowyer** [comment]
Thanks Jenn - this email is great!
It's always been my understanding that this data at some point will be public/open access - just to clarify, is the signing for the Turing's acceptable use of information technology policy because they are accessing the climate data via Azure (i.e. rather that something anyone who wants to access the data in future when it's, eg, on the MO server, will have to do?)

**Comment by RuthBowyer** [comment]
Also it would be great to ask them if they would like the data broken down into regions as this is how it will be processed (it will be much smaller relative to the whole UK)

**Comment by dingaaling** [comment]
Thanks for the feedback, Ruth! I'll send this email today.

**Comment by dingaaling** [comment]
From my perspective, Simon (Cc’d) and I will require access. Our details are:
Fliss Guest ([F.L.Guest@exeter.ac.uk](mailto:F.L.Guest@exeter.ac.uk))
Simon Kirby ([S.Kirby@exeter.ac.uk](mailto:S.Kirby@exeter.ac.uk))

**Comment by dingaaling** [comment]
Stuck because there is no form to sign, this from Tomas from RC team:

"Hi Jennifer, unfortunately, this is going to take longer than anticipated. We are still reviewing the policy and its legal implications, and it’s difficult to estimate how long the whole process will take."
