### ISSUE TITLE
Template for internal Assessment of bias correction methods

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/clim-recal#39]
We agreed with our Met Office colleagues the metrics to be used to assess bias correction methods (there's a summary of that [here)](https://hackmd.io/@rbowyer/HkPTYC9Fh). 

- MVP: 1 method
- Stretch Goal: 3 methods

I will put together an example notebook of what to be applied. Once that's done the tasks would be:

- [ ] <s>Rewrite in python (be interesting to compare assessment metrics across R and python)</s>
- [x] Incorporate python data into existing R markdown by Ruth (here: https://github.com/alan-turing-institute/clim-recal/blob/Update.Rpipeline/notebooks/Assessing_bc_data/Assessing_BC_Data.RMD). Previously in issue #60 
- [x] Run for debiased data (separately for each method or package) for the 3 cities
- [x] Check R dependencies management with @RuthBowyer 
- [x] Set up configurations for running the R notebookes
- [x] Apply the specification in #90 
- [x] Provide users options to specify what they want to look at

Note: *Don't worry about caching results*

Tess urgent for December workshop:
- [ ] There are further considerations about the variable specific metrics to use (eg how to calc drought, and precip) 

Following workshop (note before any of this can be done, need to re=run the 
- [ ] Add trend figure
- [ ] Metrics should be calculated by rankings the variables rather than day-to-day matching

**Comment by dingaaling** [comment]
Next steps:
- Upload HTML to Github to share first notebook draft

**Comment by griff-rees** [comment]
Would it make sense to tie this to #97 ?
