### ISSUE TITLE
Group files in python

### ISSUE THREAD

**Issue by aranas** [alan-turing-institute/clim-recal#49]
Grouping of files into calibration/validation/testing periods in Python. This will come from splitting the python debiasing script (`python/debiasing/run_cmethods.py`) into a grouping step and a debiasing step. The grouping step will take all input files and produce output files that are grouped into the requested time frames. The debiasing code will just run the debiasing algorithms.

**Comment by gmingas** [comment]
Overlaps with #46 . Closing
