### ISSUE TITLE
Go through fileshare and delete unnecessary data

### ISSUE THREAD

**Issue by gmingas** [alan-turing-institute/clim-recal#51]

**Comment by dingaaling** [comment]
Notes from a related issue from Ruth:
Some folders could be deleted
Rename folders
File structure to remain the same
?Move Resampled Hads data out of the Processed folder?

**Comment by RuthBowyer** [comment]
I think we can also delete the 'three.cities' files which are in `Interim/CPM/three.cities`, `Interim/HadsUK/three.cities` and `Interim/HadsUK/three.cities.greg`
as they should be superseeded by `Cropped/three.cities ` ?
