### ISSUE TITLE
Minimize `clim-recal-test` server configuration/cost

### ISSUE THREAD

**Issue by griff-rees** [alan-turing-institute/clim-recal#67]
As per the chat earlier today @gmingas: reminding myself to scale down that box as per your instruction.

**Comment by griff-rees** [comment]
Hi @gmingas and @BZ-BowenZhang. I've scaled `clim-recal-test` down to `D4ls_v5` config:

- 4 CPUs 
- 8 GBs RAM
- £0.16 per hour

@gmingas is that amenable? Feel free to tweak.

**Comment by gmingas** [comment]
Sounds good, thanks!
