### ISSUE TITLE
adding shapefiles to repo

### ISSUE THREAD

**Issue by aranas** [alan-turing-institute/clim-recal#68]
as suggested in #42 we might want to add the shapefiles to the repo to facilitate use, since the files are fairly small
They are all downloaded from OA sources but might need to double check the licenses on the sites.

- [x] verify licensing 
- [x] add note & path to file to Guidance (to section starting at line 87)
- [x] add shapefiles
- [x] add missing info on London geospatial file

**Comment by BZ-BowenZhang** [comment]
Hi @aranas, I am happy to assist with this

**Comment by BZ-BowenZhang** [comment]
@arana, I am not very sure which branch and documentation file you and Ruth are currently working on. Could you confirm this so I can add the geo files & notes there?

**Comment by dingaaling** [comment]
documentation branch has been merged into main; @BZ-BowenZhang creating new branch from current main to add new shapefiles
