### ISSUE TITLE
Replicating resampling and methods in R to compare with python

### ISSUE THREAD

**Issue by RuthBowyer** [alan-turing-institute/clim-recal#7]
- Provide docs too 
- Check resampling method

**Comment by crangelsmith** [comment]
The python resampled HADUK files are being stored in here for comparison https://dymestorage1.file.core.windows.net/vmfileshare/ClimateData/Processed/HadsUKgrid/resampled_2.2km

i’m using this grid as the baseline for the resample https://github.com/alan-turing-institute/clim-recal/blob/2-resampling/data/rcp85_land-cpm_uk_2.2km_grid.nc

**Comment by RuthBowyer** [comment]
The first pass of this is here https://github.com/alan-turing-institute/clim-recal/blob/Rrep/R/WIP-Comparing-HADs-grids.md#1-data

I need to do some more work to investigate, but as you can see there is a different in the result and alignment of the resampled grid between the two methods -  I will keep investigating - but one thing to flag is that the python-resampled file did not load with a crs, which I think might cause some issues down the line?

**Comment by RuthBowyer** [comment]
Also both resampling methods have dealt with missing vals differently which is interesting - from eyeballing I don't think either is optimum

**Comment by crangelsmith** [comment]
I think we can add the crs to the had files easily, I'll look into that.

I used the grid from a re-projected rcp file created by @AoifeHughes in November for the resampling, so this might mean that the python projection is doing something different from the R re-projection.   Is [this the code you used for this reprojection](https://github.com/alan-turing-institute/dymechh/blob/main/src/data/Reprojtobng.R)? @AoifeHughes let's take a look at it. 

If the grids are different it make sense the values of the resampled variables are different as well.

**Comment by RuthBowyer** [comment]
Awesome, thanks so much! 

> If the grids are different it make sense the values of the resampled variables are different as well

True! And just to clarify a little - I meant that if you take a look at the Cropped squares, you can see in the original Hads grid there are missing vals over (I believe water bodies). The two resampling methods I think might be considering these NAs differently in terms of how it influences the result cell value. I think, anyway! I will keep investigating

**Comment by RuthBowyer** [comment]
Hey folks - I've updated this a little [here](https://github.com/alan-turing-institute/clim-recal/blob/Rrep/R/WIP-Comparing-HADs-grids.md) 

I'm satisfied that the R reprojection/resampling of the Hads grid aligns exactly to the UKCP 2.2km data (I resampled using a reprojected UKCP grid extent - which should ignore/not consider the values within the UKCP grid - so that makes sense - apologies if I was not very clear on this step!) 

There is an issue though in how the resampling methods we've both use consider ```NA``` values in the underlying HADs grid (for some reason the resampling in ```terra``` seemed to set these to really high values! I'm sure its something I'm not understand.) It seems where the majority of HADs 1x1 cells in the corresponding 2.2km cell are ```NA```, it sets the whole cell resampled cell to ```NA```... so I could resample the resampled grid or see how to change this!

**Comment by crangelsmith** [comment]
Just an update on this for @RuthBowyer :

1. I was using a grid from an RCP re-projection done last year, in one of the first attempts from @AoifeHughes to run the projection in python. Yesterday we did some investigations on this, and the process that she is using today is equivalent to what you are doing in R with 'gdalwrap'. I think the grid is still slightly misaligned and I understand you are both meeting today to try to understand where are the differences. Once you both agree on a grid re-run the resampling on this new grid and I'll add the CRS to the saved file. 

2. About the missigness on the interpolation, I'm using the [xarray interp method](https://docs.xarray.dev/en/stable/generated/xarray.Dataset.interp.html), which has some different options for treating non-numeric values (which is what I guess the NaNs are assumed as), the default I was using is 'nearest', but there are others ("pad", "ffill", "backfill", "bfill"), I'm still trying to understand the difference between those, do you have an idea what is your R method doing in this case?.

**Comment by crangelsmith** [comment]
> Hey folks - I've updated this a little [here](https://github.com/alan-turing-institute/clim-recal/blob/Rrep/R/WIP-Comparing-HADs-grids.md)
> 
> I'm satisfied that the R reprojection/resampling of the Hads grid aligns exactly to the UKCP 2.2km data (I resampled using a reprojected UKCP grid extent -

The way I did it is to take the grid from the projected CP 2.2km data (basically the x,y coordinates) and fed that to the resampling method with the HADs data. So the grid should always align with each other.

> which should ignore/not consider the values within the UKCP grid - so that makes sense - apologies if I was not very clear on this step!)

I'm not sure what do you mean by this?

> There is an issue though in how the resampling methods we've both use consider `NA` values in the underlying HADs grid (for some reason the resampling in `terra` seemed to set these to really high values! I'm sure its something I'm not understanding). It seems where the majority of HADs 1x1 cells in the corresponding 2.2km cell are `NA`, it sets the whole cell resampled cell to `NA`... so I could resample the resampled grid or see how to change this!

Ok, thanks I think with this you answered my question number 2 above, I should understand now what is my method doing this case. What do you think is the right way to deal with this? In any case we are missing information.

**Comment by RuthBowyer** [comment]
Fab thanks @crangelsmith ! Yep @AoifeHughes and I just had a super helpful chat - I'm going to re reproject incase to was something to do with the gdal version (but we think they were about the same) - its very curious there is a difference so I'm just going to check that out a little BUT I think tbh the difference is minor between the two reprojections of the UKCP data that we might be ok. 

> The way I did it is to take the grid from the projected CP 2.2km data (basically the x,y coordinates) and fed that to the resampling method with the HADs data. So the grid should always align with each other.

Great ok! 

> > which should ignore/not consider the values within the UKCP grid - so that makes sense - apologies if I was not very clear on this step!)

>I'm not sure what do you mean by this?

Just trying to clarify my resampling just considered the grid extent rather than the values within the grid - ignore as you follow already! 

>  What do you think is the right way to deal with this? In any case we are missing information. 

I will take a look - the UKCP data has clearly used something (as you can see from the markdown, there are no missing squares in the UKCP grid) - to be using a method that considers just the cells available seems ok (but curious the HADs grid is missing data - I'm going to check the docs for this) - my assumption is HADs reflects on land estimates, in which case fine for us to ignore the 'water' cells as populations in those areas will be on land - does it make sense? 
 It is an important consideration though so once I've got a better understanding I'll chat to our met office colleagues

**Comment by RuthBowyer** [comment]
Just to update you both as I'm aware I'm not going to be 'here' again until Friday.

**UKCP 2.2km reprojected extent**

I've tried reprojecting both again in Rstudio on the vm, on cmd line on the vm (using this code), and on cmd line on my mac. The two vm runs yield the same result, but different on my mac! So I think it must be due to differences in `GDAL` and `proj` versions? 

On the vm its `GDAL 3.4.3, PROJ 8.2.0` with extent `SpatExtent : -312764.32542898, 848835.67457102, -235368.341117099, 1196831.6588829 (xmin, xmax, ymin, ymax)`
and on my mac it's `GDAL 3.4.2, PROJ 8.2.1` with extent `SpatExtent : -314780.555523748, 853419.444476252, -237705.048622294, 1198894.95137771 (xmin, xmax, ymin, ymax)`

Does feel a bit bizarre that it would not have the same extent as the versions are so similar??

The only other thing I can think is that its something to do with this warning from gdal: `Warning 1: Latitude grid not spaced evenly.  Setting projection for grid spacing is within 0.1 degrees threshold.` - so potentially there is an element of randomness for reprojection related to that 0.1 degrees threshold? 
So I think probably as long as all the UKCP data and HADs data is reprojected in the same way, this is probably fine for now (?) 

** Resampling HADS grid **

Taking a look at the `xarray` methods for NA values - seems like the default would be fine, so not sure why more cells returned as NA that the `terra` resample method (as the slight difference in grid shouldn't matter?) though? 
I'm going to see what happens using a slightly [different method](https://rdrr.io/cran/exactextractr/man/exact_resample.html) 

And then on Fri I will check the newer alignment of the UKCP grid to the resampled HADs grid? 

Thanks both!!

**Comment by crangelsmith** [comment]
> ** Resampling HADS grid **
> 
> Taking a look at the `xarray` methods for NA values - seems like the default would be fine, so not sure why more cells returned as NA that the `terra` resample method (as the slight difference in grid shouldn't matter?) though? I'm going to see what happens using a slightly [different method](https://rdrr.io/cran/exactextractr/man/exact_resample.html)
> 
> And then on Fri I will check the newer alignment of the UKCP grid to the resampled HADs grid?
> 
> Thanks both!!

Thank you @RuthBowyer! The resampled HADs file you were using in your example was using an old grid which was significantly less compatible with your grid. I'm going to recreate all the files again with the newest grid from @AoifeHughes.

I'll start with the file you've been using for comparison to check,  hopefully the differences will be smaller now.

**Comment by crangelsmith** [comment]
Hi @RuthBowyer, i recreated the resampling for the HADs tasmax variable using the new grid and making sure to store the CRS. You can find the data in the fileshare in here: `vmfileshare/ClimateData/Processed/HadsUKgrid/resampled_2.2km_newgrid/tasmax/day`. 

Could we rerun your comparison with the resampled file?

**Comment by RuthBowyer** [comment]
Thanks so much @crangelsmith  - [I have checked and the resampling grid looks great](https://github.com/alan-turing-institute/clim-recal/blob/Rrep/R/WIP-Comparing-HADs-grids.md) -the extent maps will to the UKCP grids etc. 
However, still missing cell values where the R method returns some - can't remember where you were with this, apologies?

**Comment by crangelsmith** [comment]
Hi @RuthBowyer, i'm the [xarray interp](https://docs.xarray.dev/en/stable/generated/xarray.Dataset.interp.html), with 'linear' interpolation for numerics and 'nearest' as the method for non-numeric types. 

Not sure why it is giving these differences, I'm going to play with the different options of the method and see if there is a configuration that looks closer to yours.

**Comment by crangelsmith** [comment]
In [this notebook](https://github.com/alan-turing-institute/clim-recal/blob/testing-resampling/python/resampling/testing_resampling.ipynb) i implemented the xarray resampling with different methods. The one that looks the most like the R output is the 'zero' method which according to [this article](https://stackoverflow.com/questions/27698604/what-do-the-different-values-of-the-kind-argument-mean-in-scipy-interpolate-inte) is a zero order spline. It's value at any point is the last raw value seen.

The notebook has more details but here is the summary:

Output of the 'zero' resampling with xarrays in python:

![image](https://user-images.githubusercontent.com/11162074/220135147-6dfef646-a5f5-424b-85f7-bdb9da6ec7af.png)

Output of R resampling:

![image](https://user-images.githubusercontent.com/11162074/220135248-5c8086b8-a077-4fe9-8399-c1debf4c4b9e.png)

Output of 'linear' resampling with xarrays in python:

![image](https://user-images.githubusercontent.com/11162074/220135765-6473c016-8ed0-42ab-977f-dbd108180d14.png)


I could change my method to the 'zero' spline for compatibility with the R method and rerun all the resampling. What do you think @RuthBowyer?

**Comment by RuthBowyer** [comment]
Thanks so much for this Camila! Interesting that the max and min look different between the R and python versions but it could be the scale bar, could you share the python vals? I'll take a little deep dive and might share this with James for his thoughts, but will come back with a suggestion this afternoon!

**Comment by crangelsmith** [comment]
> Thanks so much for this Camila! Interesting that the max and min look different between the R and python versions but it could be the scale bar, could you share the python vals? I'll take a little deep dive and might share this with James for his thoughts, but will come back with a suggestion this afternoon!

Hi @RuthBowyer, I updated the [notebook](https://github.com/alan-turing-institute/clim-recal/blob/testing-resampling/python/resampling/testing_resampling.ipynb) with the printed values.

**Comment by crangelsmith** [comment]
I think we agreed on an approach here, so closing this issue now.
