### ISSUE TITLE
Identify and invite target stakeholders to Dec workshop

### ISSUE THREAD

**Issue by gmingas** [alan-turing-institute/clim-recal#74]
- https://docs.google.com/document/d/1UPd1OH7kv8si5kriJXrDeGJp5ECLgJJvYwPq3pAZdBE/edit?usp=sharing
- https://hackmd.io/sGV_FSsNQAutPq-Si4-Uyg?both

**Comment by gmingas** [comment]
@dingaaling and project manager (replacing Harry) to discuss this after Jen is back

**Comment by gmingas** [comment]
Team to review agenda, as discussed in today's weekly meeting.

**Comment by dingaaling** [comment]
Invitation Template:

Subject: Invitation for UK Climate Projections (UKCP) bias correction workshop
 
Dear [INSERT NAME HERE],
 
On December 11th 2023, The Alan Turing Institute will host an in-person workshop from 10:00-16:00 at our offices in the British Library (London) focused on UKCP bias correction methods. This event aims to bring together researchers and practitioners working with climate projections data to explore different approaches to bias correction across public health, climate science, and engineering domains.
 
This workshop is being co-organised with the Met Office UKCP team including Dr Fai Fung and Dr James Pope and will feature a resource that Turing is co-developing with their team: [clim-recal](https://github.com/alan-turing-institute/clim-recal), an open repository of method comparison and guidance for bias correction of UKCP18 products. This project is led by Professor Gavin Shaddick and Professor Mark Birkin.
 
Given your expertise and your work with climate data, we would like to invite you to attend the workshop. We sincerely hope you will be able to join us and would appreciate if you could let us know by 30 November if you can attend.
 
For more information about the workshop and project, please refer to this [workshop document](https://docs.google.com/document/d/1UPd1OH7kv8si5kriJXrDeGJp5ECLgJJvYwPq3pAZdBE/edit?usp=sharing), and please do not hesitate to reach out if you have any other questions.
 
Best wishes,
Fai Fung (Met Office) and Jennifer Ding (The Alan Turing Institute)
Workshop co-organisers

**Comment by dingaaling** [comment]
Target people to invite:

From Turing/Turing partners
- Project Team: Ruth, Greg, Jen, Griff, Bowen, Sophie, Monica
- Alisha Davies
- KCL researchers?
- UA researchers?

From Met Office:
- Fai Fung
- James Pope
- Laura Dawkins

From Met Office Partners:
- Environmental/engineering consultancies
- NERC Research institutes
- University-based researchers
- Infrastructure operators

**Comment by dingaaling** [comment]
Invite List (Target: 20)

Project Team (6)
- [ ] Ruth Bowyer
- [ ] Greg Mingas
- [ ] Griffith Rees
- [ ] Bowen Zhang
- [ ] Sophie Arana
- [ ] Monica Vakil-Dewar

Met Office (3)
- [ ] Fai Fung
- [ ] James Pope
- [ ] Laura Dawkins

Met Office Stakeholders (4)
- [ ] Env/engineering consultancies
- [ ] NERC Research institutes
- [ ] University based researchers
- [ ] Infra operators

KCL (2)
- [ ]  Geographer
- [ ] Heat Physiologist

Wider Turing (5)
- [ ] Health GC?
- [ ] E&S GC?
- [ ] UA

**Comment by dingaaling** [comment]
- Need for a hybrid component

**Comment by dingaaling** [comment]
Our target participant:
- UKCP18 user
- Familiarity with Python or R
- Interest in bias correction
-

**Comment by dingaaling** [comment]
Final participant list by 24 Nov
