### ISSUE TITLE
Prepare IT/tech needs for Dec 11 workshop

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/clim-recal#80]
Thanks for the ticket @dingaaling. Hope it's ok to add some thoughts from the meeting this morning (apologies in advance if I've got any of this wrong):

- [ ] Permission for using the data for participants
  - [ ] Any forms that might need to be signed for people to have access to that data/use
  - [ ] Decide if we want people's workshop notebooks to be *saved*
    - [ ] If so how (maybe saved to folders with their names/or folders they have access to)?
    - [ ] What we provide to them something to take away (maybe safest would be a Notebook exported as HTML)
- [ ] IT infrastructure/configuration
  - [ ] How much server capacity we need to manage if say, 20 people run the model at the same time (RAM + CPU cores)
  - [ ] Configuration
    - [ ] Could try [RStudioServer](https://posit.co/products/open-source/rstudio-server/)
      - [ ] Could try extending `docker` config following this [post](https://davetang.org/muse/2021/04/24/running-rstudio-server-with-docker/),  using this `docker` [`image`](https://hub.docker.com/r/dceoy/rstudio-server/)
    - [ ] If permission is complicated could try a [`data-safe-haven`](https://github.com/alan-turing-institute/data-safe-haven) config (I've gone through some of the deployment process before...)
  - [ ] Process of mounting data (some of that is covered in the `docker` example)

**Comment by dingaaling** [comment]
- Ask people to bring their own laptop

**Comment by mvakil-dewar** [comment]
Griff is generating logins, with a few spares and we will share login details with attendees directly at the workshop.
Monica to have backup copy of credentials via Egress.
