### ISSUE TITLE
Workshop notebook preparation

### ISSUE THREAD

**Issue by griff-rees** [alan-turing-institute/clim-recal#93]
Apologies @gmingas, @RuthBowyer, and @BZ-BowenZhang and figure this is overlaps with #80 *to an extent* but here's where I got to

- [ ] #100
- [x] Rendering Kniter via `docker`
- [x] Finalise dates that are included
  - [ ] Calibration years: 1980 - 1983?
  - [ ] Validation years: 1990 - 2000
- [ ] Ease showing dates to include in the calibration
- [x] Ensure the python output is provided and tested for loading
- [x] Initial examples exploring the dataset itself
- [ ] Options to slice time periods shown in visualisation
- [ ] Options to change configuration of running the model from the top
- [x] Simplify the notebook for workshop use

**Comment by dingaaling** [comment]
@griff-rees can we close this, as the workshop preparation for the notebook has ended?
